---
apiVersion: v1
kind: Secret
metadata:
  name: ashwin-dockerhub
  annotations:
    build.pivotal.io/docker: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
stringData:
  username: pivotalashwin
  password: --------
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
secrets:
- name: ashwin-dockerhub